baseURL = "https://atwood.io"
languageCode = "en-us"
title = "Daniel Atwood"

[build]
  writeStats = true

[menu]
  [[menu.main]]
    name = "My Portfolio"
    url = "/"
    pre = "ğŸ—‚ï¸"
    weight = 10

  [[menu.main]]
    name = "My Resume"
    url = "/resume/"
    pre = "ğŸ“"
    weight = 20
  
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    pre = "ğŸ“ "
    weight = 30